### ISSUE TITLE
Reimplement Discord test?

### ISSUE THREAD

**Issue by stephenberry** [RealTimeChris/Json-Performance#1]
Thanks so much for these JSON tests and for pushing for more performant JSON handling! I've been using these tests to help optimize the code.

Anyway, I fixed the recent issue Glaze introduced with handling your Discord test, so you could reimplement it now.

**Comment by RealTimeChris** [comment]
Awesome thanks!

**Comment by RealTimeChris** [comment]
> Thanks so much for these JSON tests and for pushing for more performant JSON handling! I've been using these tests to help optimize the code.
> 
> Anyway, I fixed the recent issue Glaze introduced with handling your Discord test, so you could reimplement it now.

Alright I've re-added the Discord test. Cheers!
