### ISSUE TITLE
Unoptimal Glaze reading

### ISSUE THREAD

**Issue by stephenberry** [RealTimeChris/Json-Performance#15]
Glaze can read more efficiently when the input buffer is resizable and mutable (not const qualified).

In your benchmark code you are passing a `const std::string&` to Glaze, which forces it to use slower parsing code.

Glaze will not change any input data, but will increase the length temporarily in order to not have to do as many padding checks. The string is restored to its original state before it leaves the function call.

**Comment by stephenberry** [comment]
Just removing the `const` will give Glaze better performance when reading.

**Comment by RealTimeChris** [comment]
Alright I've just updated it to use non-const std::string references. Thanks! It should be updated in the main branch within a short while.
