### ISSUE TITLE
Jsonifier Validate Error

### ISSUE THREAD

**Issue by stephenberry** [RealTimeChris/Json-Performance#16]
I was curious why Jsonifier was showing so much faster validation than Glaze. It turns out that Glaze is properly validating the JSON, but Jsonifier's validation algorithm makes a mistake and says the JSON is invalid, which causes it to short circuit. This makes it appear to run much faster while it is actually not properly validating. You should probably make sure in your benchmark code that you look at the return value of the function and make sure it is getting the correct result.

**Comment by RealTimeChris** [comment]
Alright thanks.
