### ISSUE TITLE
Denote reading prettified vs non-prettified

### ISSUE THREAD

**Issue by stephenberry** [RealTimeChris/Json-Performance#2]
Typically, large JSON data files are minified. Glaze is optimized for reading minified data for this reason.

It's great that Jsonifier is fast at reading prettified files, but it would probably be best to compare both prettified and non-prettified parsing.

**Comment by RealTimeChris** [comment]
Done! Thanks for the suggestion.

**Comment by stephenberry** [comment]
Awesome, thanks
