### ISSUE TITLE
Glaze .minified (faster read performance)

### ISSUE THREAD

**Issue by stephenberry** [RealTimeChris/Json-Performance#4]
Like Jsonifier, Glaze now has a compile time option for when the read input is known to be minified, improving performance. Just add `.minified = true` to the read options.

Example: `glz::read<glz::opts{.minified = true}>(obj, buffer);`

Thanks for the motivation to add this feature.

**Comment by RealTimeChris** [comment]
Alright I've updated the code/benchmarks to reflect this. Thanks!
