### ISSUE TITLE
Custom vector is probably a bad idea

### ISSUE THREAD

**Issue by stephenberry** [RealTimeChris/Json-Performance#6]
Your custom vector has a lot of performance problems when it comes to implementation (I could provide specifics, but there are reserves lacking, not using noexcept move constructible, etc.). By not using std::vector you are introducing performance issues into the benchmark that cloud results.

You could always use custom allocators with std::vector if you want specific alignment.

The primary issue of not using std::vector (and an argument for using the built in allocators), is that this is the type 90% or more of other C++ libraries are using. So, you are testing code that is incompatible with the majority of other C++ code, and would require copies of data to make it compatible, which would kill performance.

You probably want the tests reflective of a normal C++ experience and not of your own vector implementation.

**Comment by RealTimeChris** [comment]
Awesome good call, thanks for letting me know about that - I've updated the results using std::vector and std::string instead of jsonifier::vector and jsonifier::string.

**Comment by stephenberry** [comment]
Nice!
