### ISSUE TITLE
Write benchmarks are misleading and are not equivalent

### ISSUE THREAD

**Issue by stephenberry** [RealTimeChris/Json-Performance#7]
I've noticed you've been making a lot of values `null`, and this appears to make Jsonifier faster. But, Glaze is often actually running faster even though the benchmarks show Jsonifier as higher MB/s. This is because Glaze by default doesn't write out null members, so it is outperforming Jsonifier, but your benchmarks only consider the data rate versus time. If I just added a bunch of whitespace to Glaze output then your benchmarks would show Glaze as much faster. This makes the benchmark pretty meaningless.

Note that if you included the runtime with your results you would probably have caught this issue.

If `null` values are important, then Glaze's option `skip_null_members` should be set to false to compare with Jsonifier.

Additionally, when writing prettified data Jsonifier writes 4 spaces versus Glaze writing 3 spaces for the indent size. This means Jsonifier writes a lot more whitespace, which artificially skews the results (this includes the prettify test). This is why removing data from tests makes Jsonifier appear faster, because there is just more whitespace processing happening for Jsonifier. The benchmarks should just use the same number of spaces for the indentation width for a proper comparison.

**Comment by RealTimeChris** [comment]
Cool thanks for letting me know - I've made the appropriate changes and updated the performance results.

**Comment by stephenberry** [comment]
Awesome, thanks!
